user:
  avatar:
    avatar_default_size: 80
    avatar_follow_size: 30
  name:
    maximum_length: 25
  email:
    minimum_length: 6
    maximum_length: 50
  password:
    minimum_length: 6
  page:
    per_page: 5
  size:
    image: 5
  word:
    maximum: 30
filter:
  learned: learned
  not_learned: not_learned
  all: get_all
